config/routes.rb
Chartsmaps::Application.routes.draw do
  resources :json_data

  root 'json_data#index'

end

app/models/json_datum.rb
class JsonDatum < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/json_data_controller.rb
class JsonDataController < ApplicationController
  before_action :set_json_datum, only: [:show, :edit, :update, :destroy]

  # GET /json_data
  # GET /json_data.json
  def index

    @json_data = JsonDatum.all
    @hash = Gmaps4rails.build_markers(@json_data) do |json_data, marker|
      marker.lat json_data.long
      marker.lng json_data.lat
    end
  end

  # GET /json_data/1
  # GET /json_data/1.json
  def show
  end

  # GET /json_data/new
  def new
    @json_datum = JsonDatum.new
  end

  # GET /json_data/1/edit
  def edit
  end

  # POST /json_data
  # POST /json_data.json
  def create
    @json_datum = JsonDatum.new(json_datum_params)

    respond_to do |format|
      if @json_datum.save
        format.html { redirect_to @json_datum, notice: 'Json datum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @json_datum }
      else
        format.html { render action: 'new' }
        format.json { render json: @json_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /json_data/1
  # PATCH/PUT /json_data/1.json
  def update
    respond_to do |format|
      if @json_datum.update(json_datum_params)
        format.html { redirect_to @json_datum, notice: 'Json datum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @json_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /json_data/1
  # DELETE /json_data/1.json
  def destroy
    @json_datum.destroy
    respond_to do |format|
      format.html { redirect_to json_data_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_json_datum
      @json_datum = JsonDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def json_datum_params
      params.require(:json_datum).permit(:value, :lat, :long)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/json_data_helper.rb
module JsonDataHelper
end

app/views/json_data/_form.html.erb
<%= form_for(@json_datum) do |f| %>
  <% if @json_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@json_datum.errors.count, "error") %> prohibited this json_datum from being saved:</h2>

      <ul>
      <% @json_datum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/json_data/edit.html.erb
<h1>Editing json_datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @json_datum %> |
<%= link_to 'Back', json_data_path %>

app/views/json_data/index.html.erb
<h1>Listing json_data</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Lat</th>
      <th>Long</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @json_data.each do |json_datum| %>
      <tr>
        <td><%= json_datum.value %></td>
        <td><%= json_datum.lat %></td>
        <td><%= json_datum.long %></td>
        <td><%= link_to 'Show', json_datum %></td>
        <td><%= link_to 'Edit', edit_json_datum_path(json_datum) %></td>
        <td><%= link_to 'Destroy', json_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= line_chart JsonDatum.group_by_minute(:created_at, "sum", "value") %>

<br>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
  
</script>
<%= link_to 'New Json datum', new_json_datum_path %>

app/views/json_data/new.html.erb
<h1>New json_datum</h1>

<%= render 'form' %>

<%= link_to 'Back', json_data_path %>

app/views/json_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @json_datum.value %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @json_datum.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @json_datum.long %>
</p>

<%= link_to 'Edit', edit_json_datum_path(@json_datum) %> |
<%= link_to 'Back', json_data_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chartsmaps</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
	<script src="javascripts/underscore-min.js"></script>
	<script src="javascripts/gmaps_google.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>